// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6IBFI25C5plnAN41y3mPk1YAAtJuEZ9s',
    appId: '1:85165658834:web:c86fa5f43fe8c078e4930b',
    messagingSenderId: '85165658834',
    projectId: 'library-125be',
    authDomain: 'library-125be.firebaseapp.com',
    storageBucket: 'library-125be.firebasestorage.app',
    measurementId: 'G-SY3085FXB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIfXi4XgPECCk1GXzreAPj-Ma6gl6bNKQ',
    appId: '1:85165658834:android:231361b4d23a504fe4930b',
    messagingSenderId: '85165658834',
    projectId: 'library-125be',
    storageBucket: 'library-125be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHEuZdfaTinPP6FA7acG5PT3GGlGnHDHM',
    appId: '1:85165658834:ios:e036096ba54dc915e4930b',
    messagingSenderId: '85165658834',
    projectId: 'library-125be',
    storageBucket: 'library-125be.firebasestorage.app',
    iosBundleId: 'com.example.libraryManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHEuZdfaTinPP6FA7acG5PT3GGlGnHDHM',
    appId: '1:85165658834:ios:e036096ba54dc915e4930b',
    messagingSenderId: '85165658834',
    projectId: 'library-125be',
    storageBucket: 'library-125be.firebasestorage.app',
    iosBundleId: 'com.example.libraryManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6IBFI25C5plnAN41y3mPk1YAAtJuEZ9s',
    appId: '1:85165658834:web:f75a7ab3e1a67ed4e4930b',
    messagingSenderId: '85165658834',
    projectId: 'library-125be',
    authDomain: 'library-125be.firebaseapp.com',
    storageBucket: 'library-125be.firebasestorage.app',
    measurementId: 'G-J69PJ037NF',
  );
}
